### ISSUE TITLE
'read_rda' has no method matching read_rda(::UTF8String)

### ISSUE THREAD

**Issue by mmagnuski** [johnmyleswhite/RDatasets.jl#32]
I tried the following:
```julia
ds = dataset("lme4", "Dyestuff")
```
which gives me the error mentioned in the title (in `.julia\v0.3\RDatasets\src\dataset.jl`)

I'm on windows 8 and have just updated to Julia 0.3.7

**Comment by mmagnuski** [comment]
Copying `dataset` function with `UTF8String` type declarations works, but then GZip throws an error:
```
ERROR: GZError(-1, "gzopen failed")
 in gzopen at C:\Users\Mikuś\.julia\v0.3\GZip\src\GZip.jl:246 (reapeats 2 times)
```

:cry:

**Comment by garborg** [comment]
@mmagnuski I'll look into this now.

@johnmyleswhite Do you mind turning on Travis for the repo? `datasets()` hasn't kept up with recent PRs, so tests are failing -- I'll fix that and add Travis config -- should keep the things in line in the future.

**Comment by johnmyleswhite** [comment]
In principle Travis should be running already: I suspect the absence of a `travis.yml` file is what's holding us back.

**Comment by garborg** [comment]
@johnmyleswhite Travis didn't take in #34. Is green in  Settings -> Webhooks & Services -> Services -> Travis green here?

**Comment by garborg** [comment]
I forget -- maybe it won't build until .travis.yml is in master.

**Comment by garborg** [comment]
@mmagnuski I just tested this on 0.3 and 0.4 using only tagged package versions, and it worked here. I'm guessing `Pkg.update()` should fix your issue. Please try, and close if it works, or share `versioninfo()` and `Pkg.status()` if it doesn't. Thanks.

**Comment by mmagnuski** [comment]
I tries `Pkg.update` but had some errors from other packages.
Now I removed `RDatasets` and then added it again. 
I am no longer getting `read_rda` error, but the `GZError(-1,"gzopen failed")`.

```
julia> versioninfo()
Julia Version 0.3.7
Commit cb9bcae* (2015-03-23 21:36 UTC)
Platform Info:
  System: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i5-3317U CPU @ 1.70GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Sandybridge)
  LAPACK: libopenblas
  LIBM: libopenlibm
  LLVM: libLLVM-3.3
```

**Comment by garborg** [comment]
How does your `Pkg.status()` look just for `RDatasets` and dependencies?
e.g. 
```julia
julia> Pkg.status()
27 required packages:
 - Compat                        0.3.7
 - DataFrames                    0.6.2
 - RDatasets                     0.1.2
64 additional packages:
 - DataArrays                    0.2.12
 - GZip                          0.2.14
```

It seems like `Pkg.update()` is having trouble updating a dependency or two.

**Comment by garborg** [comment]
(Sometimes I have to run `Pkg.update` twice, too, because it chokes the first time.)

**Comment by mmagnuski** [comment]
`Pkg.update` claims that nothing should be updated (I ran it a couple of times).
My `Pkg.status()`:
```
7 required packages:
 - GZip                          0.2.14
 - Gadfly                        0.3.11
 - Images                        0.4.35
 - Jewel                         1.0.4
 - MixedModels                   0.3.20
 - RDatasets                     0.1.2
 - Winston                       0.11.9
49 additional packages:
 - ArrayViews                    0.4.10
 - BinDeps                       0.3.9
 - Cairo                         0.2.26
 - Calculus                      0.1.6
 - Codecs                        0.1.3
   (...) 
 - DataArrays                    0.2.12
```

**Comment by randyzwitch** [comment]
This issue is so old, it can't reasonably be debugged if it's still an issue. Will be updating package, and will test for this from 0.4.6 and forward.
