### ISSUE TITLE
In Bwages the "sex" factor is loaded as all NAs

### ISSUE THREAD

**Issue by pkofod** [johnmyleswhite/RDatasets.jl#33]
When using `dataset("Ecdat", "Bwages")`, the factor "Sex" is loaded as `NA`s instead of "male"/"female".

**Comment by garborg** [comment]
Thanks for the report! I've got some other fixes almost ready to go -- I'll try to get to them and this today or tomorrow and push a patch to METADATA.

**Comment by pkofod** [comment]
Great, the data sets are nice for presenting statistics in Julia to people.

[off-topic: I used Housing to show the use of colwise(), and by() instead.]

**Comment by garborg** [comment]
I'm seeing this upstream (checked Ecdat latest, 0.2-0, and 0.1-5) -- please reopen if you find a source with valid gender data.

Re: using `Housing` -- @cgoldhammer has been improving the `DataFrames.jl` docs, but more good, salient examples always helps -- if you're free to put in a `PR` to make your examples the examples for `colwise()` and `by()` (assuming they're just a couple/few lines each), that would be greatly appreciated.

**Comment by pkofod** [comment]
Does that mean, that you can actually write `datasets("Ecdat","Bwages")` and get the sex-column filled with something else than `NA`s?

The data set can be found here http://eu.wiley.com/legacy/wileychi/verbeek2ed/datasets.html

**Comment by StoneCypher** [comment]
i think he means the place the data is coming from is where the breakage is

**Comment by garborg** [comment]
Yep, that's what I meant, but I'll bring in the right data from the link you provided if I can.
