### ISSUE TITLE
using RDatasets got LoadError: UndefVarError: @sprintf not defined

### ISSUE THREAD

**Issue by lazyjoe** [johnmyleswhite/RDatasets.jl#55]
After installing RDatasets, I tried to use "using RDatasets" and got the error.
![2018-08-19 7 08 43](https://user-images.githubusercontent.com/8591251/44308202-55f7b180-a3e3-11e8-9b86-88fc1f2903d3.png)
My julia Version 1.0.0 (2018-08-08)
os: mac OS high sierra 10.13.6
Thanks

**Comment by ikselven** [comment]
Looking at the changes in #54, this seems to be fixed in that PR.

**Comment by szcf-weiya** [comment]
Same error on Julia 1.0 for Windows 10.

**Comment by lifeskipper** [comment]
Same for Julia 1.0 on Win 7

**Comment by milunski** [comment]
Same issue for Julia 1.0 on Mac
